run:
  concurrency: 4
  tests: true

# output configuration options
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true


# all available settings of specific linters
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    check-shadowing: true
    use-installed-packages: false
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: UK
  lll:
    line-length: 120
    tab-width: 1
  unparam:
    algo: cha
    check-exported: false
  nakedret:
    max-func-lines: 30

linters:
  enable:
    - megacheck
    - govet
  enable-all: false
  disable:
    - maligned
    - prealloc
  disable-all: false
  presets:
    - bugs
    - unused
  fast: true

