language: go
go:
  - "1.10.x"
  - "1.11.x"
  - master

before_install:
  - cp .netrc ~
  - chmod 600 .netrc

install: true

before_script:
  - go install ./vengdor/github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v
  - go build